name: Run tests

on: [push]

jobs:
  test:
      name: Test
      runs-on: macOS-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Run tests
          run: swift test -v
